// Loads and normalizes feed data.
//
// Two sources:
//   data/feed.json  — the app's own content (channels + posts). Required.
//   artifacts.json  — machine-generated by the external admin app (evelabs-first).
//                     Optional, read-only, may be empty or change shape at any time.

import { displayNameFromEmail } from './ui.js';

const ORG_CHANNEL_ID = 'org';
const MAX_FACTS_PER_CARD = 4;

const state = {
  channels: [],
  posts: [],
  loaded: false,
};

async function fetchJson(url) {
  const res = await fetch(url, { cache: 'no-store' });
  if (!res.ok) throw new Error(`${url} responded ${res.status}`);
  return res.json();
}

function normalizeChannel(raw, index) {
  if (!raw || typeof raw !== 'object') return null;
  const id = String(raw.id || '').trim();
  if (!id) return null;

  const type = ['org', 'bu', 'personal'].includes(raw.type) ? raw.type : 'bu';
  return {
    id,
    type,
    name: String(raw.name || id),
    emoji: typeof raw.emoji === 'string' ? raw.emoji : '',
    description: typeof raw.description === 'string' ? raw.description : '',
    owner: typeof raw.owner === 'string' ? raw.owner.toLowerCase() : '',
    order: Number.isFinite(raw.order) ? raw.order : 100 + index,
  };
}

function normalizeFacts(raw) {
  if (!Array.isArray(raw)) return [];
  return raw
    .filter((f) => f && typeof f === 'object' && (f.label != null || f.value != null))
    .slice(0, MAX_FACTS_PER_CARD)
    .map((f) => ({ label: String(f.label ?? ''), value: String(f.value ?? '') }));
}

function normalizePost(raw, knownChannelIds, index) {
  if (!raw || typeof raw !== 'object') return null;

  const title = String(raw.title || '').trim();
  if (!title) return null;

  const id = String(raw.id || `post-${index}`);
  const channelRaw = String(raw.channel || '').trim();
  const channel = knownChannelIds.has(channelRaw) ? channelRaw : ORG_CHANNEL_ID;

  const actions = Array.isArray(raw.actions)
    ? raw.actions.filter((a) => typeof a === 'string' && a.trim()).slice(0, 4)
    : [];

  return {
    id,
    channel,
    title,
    description: typeof raw.description === 'string' ? raw.description : '',
    facts: normalizeFacts(raw.facts),
    artifactUrl: typeof raw.artifactUrl === 'string' ? raw.artifactUrl : '',
    author: typeof raw.author === 'string' ? raw.author : '',
    publishedAt: typeof raw.publishedAt === 'string' ? raw.publishedAt : '',
    actions,
    source: 'feed',
  };
}

// Map an artifacts.json entry ({url, title, description?, addedAt}) onto a minimal org post.
function artifactToPost(raw, index) {
  if (!raw || typeof raw !== 'object') return null;
  const title = String(raw.title || '').trim();
  const url = String(raw.url || '').trim();
  if (!title || !url) return null;

  return {
    id: `artifact-${index}-${title.slice(0, 40)}`,
    channel: ORG_CHANNEL_ID,
    title,
    description: typeof raw.description === 'string' ? raw.description : '',
    facts: [],
    artifactUrl: url,
    author: '',
    publishedAt: typeof raw.addedAt === 'string' ? raw.addedAt : '',
    actions: [],
    source: 'artifacts',
  };
}

function sortPosts(posts) {
  return posts.slice().sort((a, b) => {
    const ta = Date.parse(a.publishedAt) || 0;
    const tb = Date.parse(b.publishedAt) || 0;
    return tb - ta;
  });
}

export async function loadAll() {
  const [feedResult, artifactsResult] = await Promise.allSettled([
    fetchJson('./data/feed.json'),
    fetchJson('./artifacts.json'),
  ]);

  if (feedResult.status !== 'fulfilled') {
    state.loaded = false;
    throw new Error('Feed unavailable');
  }

  const feed = feedResult.value || {};
  const channels = (Array.isArray(feed.channels) ? feed.channels : [])
    .map(normalizeChannel)
    .filter(Boolean);

  // Guarantee an org channel exists so orphaned posts always have a home.
  if (!channels.some((c) => c.id === ORG_CHANNEL_ID)) {
    channels.unshift({
      id: ORG_CHANNEL_ID,
      type: 'org',
      name: 'Bria',
      emoji: '🏛',
      description: '',
      owner: '',
      order: 0,
    });
  }

  const knownIds = new Set(channels.map((c) => c.id));
  const posts = (Array.isArray(feed.posts) ? feed.posts : [])
    .map((p, i) => normalizePost(p, knownIds, i))
    .filter(Boolean);

  if (artifactsResult.status === 'fulfilled' && Array.isArray(artifactsResult.value)) {
    const seenUrls = new Set(posts.map((p) => p.artifactUrl).filter(Boolean));
    artifactsResult.value.forEach((raw, i) => {
      const post = artifactToPost(raw, i);
      if (post && !seenUrls.has(post.artifactUrl)) {
        seenUrls.add(post.artifactUrl);
        posts.push(post);
      }
    });
  }

  state.channels = channels.sort((a, b) => a.order - b.order);
  state.posts = sortPosts(posts);
  state.loaded = true;

  return { channels: state.channels, posts: state.posts };
}

// Channels in display order, with the signed-in user's personal channel first and flagged.
// If the user has no personal channel yet, synthesize an empty one so "My channel" always exists.
export function getChannels(user) {
  const email = String(user?.email || '').toLowerCase();
  const channels = state.channels.slice();

  let mine = email ? channels.find((c) => c.type === 'personal' && c.owner === email) : null;

  if (email && !mine) {
    mine = {
      id: `u-${email.split('@')[0]}`,
      type: 'personal',
      name: user?.name || displayNameFromEmail(email),
      emoji: '👤',
      description: 'Your personal channel — nothing published here yet.',
      owner: email,
      order: 10,
      synthesized: true,
    };
    channels.push(mine);
  }

  return channels
    .map((c) => ({ ...c, mine: Boolean(mine) && c.id === mine.id }))
    .sort((a, b) => {
      if (a.mine !== b.mine) return a.mine ? -1 : 1;
      return a.order - b.order;
    });
}

export function getPosts(channelId) {
  if (!channelId || channelId === 'all') return state.posts;
  return state.posts.filter((p) => p.channel === channelId);
}

export function getPost(id) {
  return state.posts.find((p) => p.id === id) || null;
}

export function getChannel(id) {
  return state.channels.find((c) => c.id === id) || null;
}
