// Loads and normalizes feed data.
//
// Two sources:
//   data/feed.json  — the app's own content (channels + posts). Required.
//   artifacts.json  — machine-generated by the external admin app (evelabs-first).
//                     Optional, read-only, may be empty or change shape at any time.

import { displayNameFromEmail } from './ui.js';

const ORG_CHANNEL_ID = 'org';
const MAX_FACTS_PER_CARD = 4;

// How far down the org a post is aimed. A company number tells an engineer
// nothing about their Tuesday, so every post declares the altitude it speaks at
// and the feed can be filtered to the one the reader actually acts on.
export const LEVELS = ['company', 'function', 'team', 'me'];
const DEFAULT_LEVEL = 'function';

const state = {
  channels: [],
  posts: [],
  loaded: false,
};

async function fetchJson(url) {
  const res = await fetch(url, { cache: 'no-store' });
  if (!res.ok) throw new Error(`${url} responded ${res.status}`);
  return res.json();
}

function normalizeChannel(raw, index) {
  if (!raw || typeof raw !== 'object') return null;
  const id = String(raw.id || '').trim();
  if (!id) return null;

  const type = ['org', 'bu', 'personal'].includes(raw.type) ? raw.type : 'bu';
  return {
    id,
    type,
    name: String(raw.name || id),
    emoji: typeof raw.emoji === 'string' ? raw.emoji : '',
    description: typeof raw.description === 'string' ? raw.description : '',
    owner: typeof raw.owner === 'string' ? raw.owner.toLowerCase() : '',
    order: Number.isFinite(raw.order) ? raw.order : 100 + index,
  };
}

function normalizeFacts(raw) {
  if (!Array.isArray(raw)) return [];
  return raw
    .filter((f) => f && typeof f === 'object' && (f.label != null || f.value != null))
    .slice(0, MAX_FACTS_PER_CARD)
    .map((f) => ({ label: String(f.label ?? ''), value: String(f.value ?? '') }));
}

// A number without a target and a date is not allowed on this feed — that is
// the house rule. The checker enforces presence; this only normalizes shape.
function normalizeTarget(raw) {
  if (!raw || typeof raw !== 'object') return null;
  const value = String(raw.value || '').trim();
  const by = String(raw.by || '').trim();
  if (!value || !by) return null;
  return { value, by };
}

// A task is not a task until it has an owner, a deadline, and milestones that
// keep the next action inside an ~18-hour window. "TBN" is a valid owner value
// precisely so the gap renders red instead of hiding.
function normalizeTask(raw) {
  if (!raw || typeof raw !== 'object') return null;
  const owner = String(raw.owner || '').trim();
  const due = String(raw.due || '').trim();
  const milestones = (Array.isArray(raw.milestones) ? raw.milestones : [])
    .filter((m) => m && typeof m === 'object' && m.what && m.due)
    .map((m) => ({
      what: String(m.what),
      due: String(m.due),
      done: m.done === true,
    }));
  if (!owner || !due || milestones.length === 0) return null;
  return { owner, due, milestones };
}

// Charts are only rendered from data that's actually present and numeric —
// a malformed chart is dropped rather than drawn from partial values.
function normalizeChart(raw) {
  if (!raw || typeof raw !== 'object') return null;

  if (raw.type === 'line') {
    const values = Array.isArray(raw.values) ? raw.values.filter(Number.isFinite) : [];
    if (values.length < 2) return null;
    return {
      type: 'line',
      label: String(raw.label || ''),
      from: String(raw.from || ''),
      to: String(raw.to || ''),
      partialLast: raw.partialLast === true,
      values,
    };
  }

  if (raw.type === 'proportion') {
    const segments = (Array.isArray(raw.segments) ? raw.segments : [])
      .filter((s) => s && Number.isFinite(s.value) && s.value > 0)
      .map((s) => ({
        label: String(s.label || ''),
        value: s.value,
        tone: ['good', 'partial', 'bad'].includes(s.tone) ? s.tone : 'partial',
      }));
    if (segments.length === 0) return null;
    return { type: 'proportion', label: String(raw.label || ''), segments };
  }

  return null;
}

function normalizePost(raw, knownChannelIds, index) {
  if (!raw || typeof raw !== 'object') return null;

  const title = String(raw.title || '').trim();
  if (!title) return null;

  const id = String(raw.id || `post-${index}`);
  const channelRaw = String(raw.channel || '').trim();
  const channel = knownChannelIds.has(channelRaw) ? channelRaw : ORG_CHANNEL_ID;

  const actions = Array.isArray(raw.actions)
    ? raw.actions.filter((a) => typeof a === 'string' && a.trim()).slice(0, 4)
    : [];

  return {
    id,
    channel,
    title,
    description: typeof raw.description === 'string' ? raw.description : '',
    facts: normalizeFacts(raw.facts),
    chart: normalizeChart(raw.chart),
    target: normalizeTarget(raw.target),
    task: normalizeTask(raw.task),
    level: LEVELS.includes(raw.level) ? raw.level : DEFAULT_LEVEL,
    // Who this is actually for at the "me" level — an email, or a role name.
    owner: typeof raw.owner === 'string' ? raw.owner.toLowerCase() : '',
    // Where the numbers came from, shown on the card.
    source: typeof raw.source === 'string' ? raw.source : '',
    artifactUrl: typeof raw.artifactUrl === 'string' ? raw.artifactUrl : '',
    author: typeof raw.author === 'string' ? raw.author : '',
    publishedAt: typeof raw.publishedAt === 'string' ? raw.publishedAt : '',
    actions,
    origin: 'feed',
  };
}

// Map an artifacts.json entry ({url, title, description?, addedAt}) onto a minimal org post.
function artifactToPost(raw, index) {
  if (!raw || typeof raw !== 'object') return null;
  const title = String(raw.title || '').trim();
  const url = String(raw.url || '').trim();
  if (!title || !url) return null;

  return {
    id: `artifact-${index}-${title.slice(0, 40)}`,
    channel: ORG_CHANNEL_ID,
    title,
    description: typeof raw.description === 'string' ? raw.description : '',
    facts: [],
    target: null,
    task: null,
    level: DEFAULT_LEVEL,
    owner: '',
    artifactUrl: url,
    author: '',
    publishedAt: typeof raw.addedAt === 'string' ? raw.addedAt : '',
    actions: [],
    source: '',
    origin: 'artifacts',
  };
}

function sortPosts(posts) {
  return posts.slice().sort((a, b) => {
    const ta = Date.parse(a.publishedAt) || 0;
    const tb = Date.parse(b.publishedAt) || 0;
    return tb - ta;
  });
}

export async function loadAll() {
  const [feedResult, artifactsResult] = await Promise.allSettled([
    fetchJson('./data/feed.json'),
    fetchJson('./artifacts.json'),
  ]);

  if (feedResult.status !== 'fulfilled') {
    state.loaded = false;
    throw new Error('Feed unavailable');
  }

  const feed = feedResult.value || {};
  const channels = (Array.isArray(feed.channels) ? feed.channels : [])
    .map(normalizeChannel)
    .filter(Boolean);

  // Guarantee an org channel exists so orphaned posts always have a home.
  if (!channels.some((c) => c.id === ORG_CHANNEL_ID)) {
    channels.unshift({
      id: ORG_CHANNEL_ID,
      type: 'org',
      name: 'Bria',
      emoji: '🏛',
      description: '',
      owner: '',
      order: 0,
    });
  }

  const knownIds = new Set(channels.map((c) => c.id));
  const posts = (Array.isArray(feed.posts) ? feed.posts : [])
    .map((p, i) => normalizePost(p, knownIds, i))
    .filter(Boolean);

  if (artifactsResult.status === 'fulfilled' && Array.isArray(artifactsResult.value)) {
    const seenUrls = new Set(posts.map((p) => p.artifactUrl).filter(Boolean));
    artifactsResult.value.forEach((raw, i) => {
      const post = artifactToPost(raw, i);
      if (post && !seenUrls.has(post.artifactUrl)) {
        seenUrls.add(post.artifactUrl);
        posts.push(post);
      }
    });
  }

  state.channels = channels.sort((a, b) => a.order - b.order);
  state.posts = sortPosts(posts);
  state.loaded = true;

  return { channels: state.channels, posts: state.posts };
}

// Channels in display order, with the signed-in user's personal channel first and flagged.
// If the user has no personal channel yet, synthesize an empty one so "My channel" always exists.
export function getChannels(user) {
  const email = String(user?.email || '').toLowerCase();
  const channels = state.channels.slice();

  let mine = email ? channels.find((c) => c.type === 'personal' && c.owner === email) : null;

  if (email && !mine) {
    mine = {
      id: `u-${email.split('@')[0]}`,
      type: 'personal',
      name: user?.name || displayNameFromEmail(email),
      emoji: '👤',
      description: 'Your personal channel — nothing published here yet.',
      owner: email,
      order: 10,
      synthesized: true,
    };
    channels.push(mine);
  }

  return channels
    .map((c) => ({ ...c, mine: Boolean(mine) && c.id === mine.id }))
    .sort((a, b) => {
      if (a.mine !== b.mine) return a.mine ? -1 : 1;
      return a.order - b.order;
    });
}

// Channel is what the post is about; level is how far down it reaches. They're
// independent filters — "R&D, at my level" is a different question from either
// one alone. At the "me" level a signed-in user sees only posts addressed to
// them, since that is the whole point of the altitude.
export function getPosts(channelId, level, user) {
  let posts = state.posts;

  if (channelId && channelId !== 'all') {
    posts = posts.filter((p) => p.channel === channelId);
  }

  if (level && level !== 'all') {
    posts = posts.filter((p) => p.level === level);
    if (level === 'me') {
      const email = String(user?.email || '').toLowerCase();
      posts = posts.filter((p) => !p.owner || p.owner === email);
    }
  }

  return posts;
}

// How many posts sit at each level, for the filter row — a level with nothing
// behind it should say so rather than leading somewhere empty.
// Counts must be what the filter would actually return, owner rule included —
// a chip reading "Me 1" over an empty grid is worse than no count at all.
export function countByLevel(channelId, user) {
  const counts = { all: getPosts(channelId, 'all', user).length };
  for (const level of LEVELS) {
    counts[level] = getPosts(channelId, level, user).length;
  }
  return counts;
}

export function getPost(id) {
  return state.posts.find((p) => p.id === id) || null;
}

export function getChannel(id) {
  return state.channels.find((c) => c.id === id) || null;
}
